PyErr_Print(void)
{
    PyErr_PrintEx(1);
}